/**
 * The Product class represents a product entity in the application.
 * It contains information about a product, including its name, description, price, and stock quantity.
 */
package org.example.Model;

/**
 * A class representing a product entity.
 */
public class Product {
    private Long productId; // ID of the product
    private String productName; // Name of the product
    private String productDescription; // Description of the product
    private double productPrice; // Price of the product
    private int productStock; // Stock quantity of the product

    /**
     * Default constructor.
     */
    public Product() {
    }

    /**
     * Constructor with all fields.
     *
     * @param productId          The ID of the product.
     * @param productName        The name of the product.
     * @param productDescription The description of the product.
     * @param productPrice       The price of the product.
     * @param productStock       The stock quantity of the product.
     */
    public Product(Long productId, String productName, String productDescription, double productPrice, int productStock) {
        this.productId = productId;
        this.productName = productName;
        this.productDescription = productDescription;
        this.productPrice = productPrice;
        this.productStock = productStock;
    }

    /**
     * Constructor without productId (useful for insertion where productId is generated by the database).
     *
     * @param productName        The name of the product.
     * @param productDescription The description of the product.
     * @param productPrice       The price of the product.
     * @param productStock       The stock quantity of the product.
     */
    public Product(String productName, String productDescription, double productPrice, int productStock) {
        this.productName = productName;
        this.productDescription = productDescription;
        this.productPrice = productPrice;
        this.productStock = productStock;
    }

    /**
     * Provides a string representation of the Product object.
     *
     * @return A string representation of the Product object.
     */
    @Override
    public String toString() {
        return "Product{" +
                "productId=" + productId +
                ", productName='" + productName + '\'' +
                ", productDescription='" + productDescription + '\'' +
                ", productPrice=" + productPrice +
                ", productStock=" + productStock +
                '}';
    }

    /**
     * Retrieves the ID of the product.
     *
     * @return The ID of the product.
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * Sets the ID of the product.
     *
     * @param productId The ID of the product.
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * Retrieves the name of the product.
     *
     * @return The name of the product.
     */
    public String getProductName() {
        return productName;
    }

    /**
     * Sets the name of the product.
     *
     * @param productName The name of the product.
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * Retrieves the description of the product.
     *
     * @return The description of the product.
     */
    public String getProductDescription() {
        return productDescription;
    }

    /**
     * Sets the description of the product.
     *
     * @param productDescription The description of the product.
     */
    public void setProductDescription(String productDescription) {
        this.productDescription = productDescription;
    }

    /**
     * Retrieves the price of the product.
     *
     * @return The price of the product.
     */
    public double getProductPrice() {
        return productPrice;
    }

    /**
     * Sets the price of the product.
     *
     * @param productPrice The price of the product.
     */
    public void setProductPrice(double productPrice) {
        this.productPrice = productPrice;
    }

    /**
     * Retrieves the stock quantity of the product.
     *
     * @return The stock quantity of the product.
     */
    public int getProductStock() {
        return productStock;
    }

    /**
     * Sets the stock quantity of the product.
     *
     * @param productStock The stock quantity of the product.
     */
    public void setProductStock(int productStock) {
        this.productStock = productStock;
    }
}
