/**
 * The User class represents a user entity in the application.
 * It contains information about a user, including their username, password, name, address, contact details, and role.
 */
package org.example.Model;

/**
 * A class representing a user entity.
 */
public class User {
    private Long userId; // ID of the user
    private String username; // Username of the user
    private String password; // Password of the user
    private String firstName; // First name of the user
    private String lastName; // Last name of the user
    private String address; // Address of the user
    private String email; // Email address of the user
    private String phoneNumber; // Phone number of the user
    private String role; // Role of the user

    /**
     * Constructor with all fields.
     *
     * @param userId       The ID of the user.
     * @param username     The username of the user.
     * @param password     The password of the user.
     * @param firstName    The first name of the user.
     * @param lastName     The last name of the user.
     * @param address      The address of the user.
     * @param email        The email address of the user.
     * @param phoneNumber  The phone number of the user.
     * @param role         The role of the user.
     */
    public User(Long userId, String username, String password, String firstName, String lastName, String address, String email, String phoneNumber, String role) {
        this.userId = userId;
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.role = role;
    }

    /**
     * Constructor without userId (useful for insertion where userId is generated by the database).
     *
     * @param username     The username of the user.
     * @param password     The password of the user.
     * @param firstName    The first name of the user.
     * @param lastName     The last name of the user.
     * @param address      The address of the user.
     * @param email        The email address of the user.
     * @param phoneNumber  The phone number of the user.
     * @param role         The role of the user.
     */
    public User(String username, String password, String firstName, String lastName, String address, String email, String phoneNumber, String role) {
        this.username = username;
        this.password = password;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.role = role;
    }

    /**
     * Default constructor.
     */
    public User() {
    }

    /**
     * Provides a string representation of the User object.
     *
     * @return A string representation of the User object.
     */
    @Override
    public String toString() {
        return "User{" +
                "userId=" + userId +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", address='" + address + '\'' +
                ", email='" + email + '\'' +
                ", phoneNumber='" + phoneNumber + '\'' +
                ", role='" + role + '\'' +
                '}';
    }

    /**
     * Retrieves the ID of the user.
     *
     * @return The ID of the user.
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * Sets the ID of the user.
     *
     * @param userId The ID of the user.
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * Retrieves the username of the user.
     *
     * @return The username of the user.
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the username of the user.
     *
     * @param username The username of the user.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Retrieves the password of the user.
     *
     * @return The password of the user.
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the password of the user.
     *
     * @param password The password of the user.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Retrieves the first name of the user.
     *
     * @return The first name of the user.
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the first name of the user.
     *
     * @param firstName The first name of the user.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * Retrieves the last name of the user.
     *
     * @return The last name of the user.
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the last name of the user.
     *
     * @param lastName The last name of the user.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * Retrieves the address of the user.
     *
     * @return The address of the user.
     */
    public String getAddress() {
        return address;
    }

    /**
     * Sets the address of the user.
     *
     * @param address The address of the user.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * Retrieves the email address of the user.
     *
     * @return The email address of the user.
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the email address of the user.
     *
     * @param email The email address of the user.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * Retrieves the phone number of the user.
     *
     * @return The phone number of the user.
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * Sets the phone number of the user.
     *
     * @param phoneNumber The phone number of the user.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * Retrieves the role of the user.
     *
     * @return The role of the user.
     */
    public String getRole() {
        return role;
    }

    /**
     * Sets the role of the user.
     *
     * @param role The role of the user.
     */
    public void setRole(String role) {
        this.role = role;
    }
}
